# Generated by Django 5.1.6 on 2025-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static\\images\x08ase_profile_pic.png', upload_to=''),
        ),
    ]
