# Generated by Django 5.1.7 on 2025-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_alter_graphictitle_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_graphic_titles',
            field=models.ManyToManyField(blank=True, to='titles.graphictitle', verbose_name='Любимые комиксы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_text_titles',
            field=models.ManyToManyField(blank=True, to='titles.texttitle', verbose_name='Любимые новеллы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='titles_read_amount',
            field=models.IntegerField(default=0, verbose_name='Количество прочитанных тайтлов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_avatars', verbose_name='Аватарка пользователя'),
        ),
    ]
