# Generated by Django 5.1.6 on 2025-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_avatar_userprofile_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_pic',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_images'),
        ),
    ]
