# Generated by Django 5.1.6 on 2025-02-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_user_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_pic',
            new_name='user_avatar',
        ),
    ]
