# Generated by Django 5.1.6 on 2025-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_pic_userprofile_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_avatars'),
        ),
    ]
