# Generated by Django 5.1.7 on 2025-04-10 19:08

import django.db.models.deletion
import titles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name_rus', models.CharField(max_length=100, unique=True)),
                ('title_name_eng', models.CharField(blank=True, max_length=100, unique=True)),
                ('title_author', models.CharField(max_length=100)),
                ('title_is_ongoing', models.BooleanField(default=True)),
                ('title_description', models.TextField()),
                ('publication_year', models.PositiveSmallIntegerField(default=2025)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('title_cover', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to=titles.models.get_graphic_title_cover_path)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('publication_year__lte', 2025), ('publication_year__gt', 0)), name='0 < publication year <= current year (graphic)')],
            },
        ),
        migrations.CreateModel(
            name='GraphicTitleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(blank=True, max_length=255)),
                ('chapter_number', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_chapters', to='titles.graphictitle')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicTitlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=titles.models.get_graphic_chapter_path)),
                ('page_number', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='titles.graphictitlechapter')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='TextTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name_rus', models.CharField(max_length=100, unique=True)),
                ('title_name_eng', models.CharField(blank=True, max_length=100, unique=True)),
                ('title_author', models.CharField(max_length=100)),
                ('title_is_ongoing', models.BooleanField(default=True)),
                ('title_description', models.TextField()),
                ('publication_year', models.PositiveSmallIntegerField(default=2025)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('title_cover', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to=titles.models.get_text_title_cover_path)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('publication_year__lte', 2025), ('publication_year__gt', 0)), name='0 < publication year <= current year (text)')],
            },
        ),
        migrations.CreateModel(
            name='TextTitleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(blank=True, max_length=255)),
                ('chapter_number', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.FileField(upload_to=titles.models.get_text_chapter_path)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_chapters', to='titles.texttitle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='graphictitlechapter',
            constraint=models.UniqueConstraint(fields=('title', 'chapter_number'), name='unique_chapter_number_per_graphic_title'),
        ),
        migrations.AddConstraint(
            model_name='graphictitlepage',
            constraint=models.UniqueConstraint(fields=('chapter', 'page_number'), name='unique_page_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='texttitlechapter',
            constraint=models.UniqueConstraint(fields=('title', 'chapter_number'), name='unique_chapter_number_per_text_title'),
        ),
    ]
