# Generated by Django 5.1.7 on 2025-04-11 10:33

import titles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_graphictitlechapter_display_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphictitle',
            name='title_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to=titles.models.get_graphic_title_cover_path),
        ),
    ]
