# Generated by Django 5.1.7 on 2025-04-11 10:36

import titles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_graphictitle_title_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttitle',
            name='title_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to=titles.models.get_text_title_cover_path),
        ),
    ]
