# Generated by Django 5.1.7 on 2025-04-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_alter_texttitle_title_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphictitlechapter',
            name='chapter_number',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='chapter_number',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
