# Generated by Django 5.1.7 on 2025-04-13 22:18

import django.db.models.deletion
import titles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_alter_graphictitlechapter_chapter_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphictitle',
            options={'verbose_name': 'Комикс', 'verbose_name_plural': 'Комиксы'},
        ),
        migrations.AlterModelOptions(
            name='graphictitlechapter',
            options={'verbose_name': 'Глава комикса', 'verbose_name_plural': 'Главы комиксов'},
        ),
        migrations.AlterModelOptions(
            name='graphictitlepage',
            options={'ordering': ['page_number'], 'verbose_name': 'Страница комикса', 'verbose_name_plural': 'Страницы комиксов'},
        ),
        migrations.AlterModelOptions(
            name='texttitle',
            options={'verbose_name': 'Новелла', 'verbose_name_plural': 'Новеллы'},
        ),
        migrations.AlterModelOptions(
            name='texttitlechapter',
            options={'verbose_name': 'Глава новеллы', 'verbose_name_plural': 'Главы новелл'},
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество людей, добавивших в избранное'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to=titles.models.get_graphic_title_cover_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_is_ongoing',
            field=models.BooleanField(default=True, verbose_name='Статус (продолжается - галочка, закончено - пусто)'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_name_eng',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название тайтла (английское)'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_name_rus',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название тайтла'),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='graphictitlechapter',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='graphictitlechapter',
            name='chapter_number',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Фактический номер главы'),
        ),
        migrations.AlterField(
            model_name='graphictitlechapter',
            name='display_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер главы для отображения'),
        ),
        migrations.AlterField(
            model_name='graphictitlechapter',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_chapters', to='titles.graphictitle', verbose_name='Связанный тайтл'),
        ),
        migrations.AlterField(
            model_name='graphictitlechapter',
            name='volume',
            field=models.PositiveIntegerField(default=1, verbose_name='Том главы'),
        ),
        migrations.AlterField(
            model_name='graphictitlepage',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='titles.graphictitlechapter', verbose_name='Связанная глава'),
        ),
        migrations.AlterField(
            model_name='graphictitlepage',
            name='image',
            field=models.ImageField(upload_to=titles.models.get_graphic_chapter_path, verbose_name='Страница (изображение)'),
        ),
        migrations.AlterField(
            model_name='graphictitlepage',
            name='page_number',
            field=models.PositiveIntegerField(verbose_name='Номер страницы'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество людей, добавивших в избранное'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to=titles.models.get_text_title_cover_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_is_ongoing',
            field=models.BooleanField(default=True, verbose_name='Статус (продолжается - галочка, закончено - пусто)'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_name_eng',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название тайтла (английское)'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_name_rus',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название тайтла'),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='chapter_number',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Фактический номер главы'),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='display_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер главы для отображения'),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='text_content',
            field=models.FileField(upload_to=titles.models.get_text_chapter_path, verbose_name='Содержимое главы'),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_chapters', to='titles.texttitle', verbose_name='Связанный тайтл'),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='volume',
            field=models.PositiveIntegerField(default=1, verbose_name='Том главы'),
        ),
    ]
