# Generated by Django 5.1.7 on 2025-04-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_alter_graphictitle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphictitle',
            options={'ordering': ['added_at'], 'verbose_name': 'Комикс', 'verbose_name_plural': 'Комиксы'},
        ),
        migrations.AlterModelOptions(
            name='texttitle',
            options={'ordering': ['added_at'], 'verbose_name': 'Новелла', 'verbose_name_plural': 'Новеллы'},
        ),
    ]
