# Generated by Django 5.1.7 on 2025-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_alter_graphictitle_options_alter_texttitle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphictitle',
            options={'ordering': ['-added_at'], 'verbose_name': 'Комикс', 'verbose_name_plural': 'Комиксы'},
        ),
        migrations.AlterModelOptions(
            name='texttitle',
            options={'ordering': ['-added_at'], 'verbose_name': 'Новелла', 'verbose_name_plural': 'Новеллы'},
        ),
        migrations.AddIndex(
            model_name='graphictitle',
            index=models.Index(fields=['-added_at'], name='titles_grap_added_a_1428a6_idx'),
        ),
        migrations.AddIndex(
            model_name='graphictitle',
            index=models.Index(fields=['publication_year'], name='titles_grap_publica_58fb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='texttitle',
            index=models.Index(fields=['-added_at'], name='titles_text_added_a_88db8f_idx'),
        ),
        migrations.AddIndex(
            model_name='texttitle',
            index=models.Index(fields=['publication_year'], name='titles_text_publica_217687_idx'),
        ),
    ]
