# Generated by Django 5.1.6 on 2025-03-26 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_titlechapter_options_and_more'),
        ('reader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphicTitleFavorites',
            new_name='GraphicTitleFavorite',
        ),
        migrations.RenameModel(
            old_name='GraphicTitleViews',
            new_name='GraphicTitleView',
        ),
        migrations.RenameModel(
            old_name='TextTitleBookmarks',
            new_name='TextTitleBookmark',
        ),
        migrations.RenameModel(
            old_name='TextTitleFavorites',
            new_name='TextTitleFavorite',
        ),
        migrations.RenameModel(
            old_name='TextTitleViews',
            new_name='TextTitleView',
        ),
    ]
