# Generated by Django 5.1.7 on 2025-04-10 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reader', '0001_initial'),
        ('titles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graphictitlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graphictitlefavorite',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.graphictitle'),
        ),
        migrations.AddField(
            model_name='graphictitlefavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graphictitleview',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_viewers', to='titles.graphictitle'),
        ),
        migrations.AddField(
            model_name='graphictitleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texttitlebookmark',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.texttitlechapter'),
        ),
        migrations.AddField(
            model_name='texttitlebookmark',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.texttitle'),
        ),
        migrations.AddField(
            model_name='texttitlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texttitlefavorite',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.texttitle'),
        ),
        migrations.AddField(
            model_name='texttitlefavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texttitleview',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_viewers', to='titles.texttitle'),
        ),
        migrations.AddField(
            model_name='texttitleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
