# Generated by Django 5.1.7 on 2025-03-31 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_graphictitle_title_cover_texttitle_title_cover'),
        ('reader', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graphictitlefavorite',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texttitlefavorite',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphictitlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='graphictitlefavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='graphictitleview',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_viewers', to='main.graphictitle'),
        ),
        migrations.AlterField(
            model_name='graphictitleview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texttitlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texttitlefavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texttitleview',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_viewers', to='main.texttitle'),
        ),
        migrations.AlterField(
            model_name='texttitleview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
