# Generated by Django 5.1.7 on 2025-04-10 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_initial'),
        ('titles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphictitleview',
            name='title',
        ),
        migrations.RemoveField(
            model_name='graphictitleview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='texttitlefavorite',
            name='title',
        ),
        migrations.RemoveField(
            model_name='texttitlefavorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='texttitleview',
            name='title',
        ),
        migrations.RemoveField(
            model_name='texttitleview',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='graphictitlebookmark',
            unique_together={('user', 'title', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='texttitlebookmark',
            unique_together={('user', 'title', 'chapter')},
        ),
        migrations.DeleteModel(
            name='GraphicTitleFavorite',
        ),
        migrations.DeleteModel(
            name='GraphicTitleView',
        ),
        migrations.DeleteModel(
            name='TextTitleFavorite',
        ),
        migrations.DeleteModel(
            name='TextTitleView',
        ),
    ]
