# Generated by Django 5.1.7 on 2025-04-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_graphictitlefavorite_time_texttitlefavorite_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphictitleview',
            name='user_ip',
            field=models.CharField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texttitleview',
            name='user_ip',
            field=models.CharField(default='0'),
            preserve_default=False,
        ),
    ]
