# Generated by Django 5.1.7 on 2025-05-06 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reader', '0003_remove_graphictitleview_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='texttitlebookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='texttitlebookmark',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='texttitlebookmark',
            name='title',
        ),
        migrations.RemoveField(
            model_name='texttitlebookmark',
            name='user',
        ),
        migrations.CreateModel(
            name='TitleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('chapter_number', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Номер главы')),
                ('page_number', models.PositiveIntegerField(blank=True, verbose_name='Номер страницы')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.DeleteModel(
            name='GraphicTitleBookmark',
        ),
        migrations.DeleteModel(
            name='TextTitleBookmark',
        ),
    ]
