# Generated by Django 5.1.7 on 2025-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_alter_texttitlebookmark_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlebookmark',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер страницы'),
        ),
    ]
