# Generated by Django 5.1.7 on 2025-05-06 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_alter_titlebookmark_page_number'),
        ('titles', '0009_alter_graphictitle_options_alter_texttitle_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicTitleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.graphictitlechapter')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.graphictitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='TextTitleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.texttitlechapter')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.texttitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title', 'chapter')},
            },
        ),
        migrations.DeleteModel(
            name='TitleBookmark',
        ),
    ]
