# Generated by Django 5.1.7 on 2025-05-06 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_graphictitlebookmark_texttitlebookmark_and_more'),
        ('titles', '0009_alter_graphictitle_options_alter_texttitle_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphictitlebookmark',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='texttitlebookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='graphictitlebookmark',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='titles.graphictitlepage'),
        ),
        migrations.AlterField(
            model_name='graphictitlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texttitlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='graphictitlebookmark',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='texttitlebookmark',
            unique_together={('user', 'title')},
        ),
    ]
