# Generated by Django 5.1.7 on 2025-04-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlerating',
            options={'verbose_name': 'Оценка тайтла', 'verbose_name_plural': 'Оценки тайтлов'},
        ),
    ]
