# Generated by Django 5.1.7 on 2025-04-19 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ratings', '0002_alter_titlerating_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titlerating',
            name='rate only once',
        ),
        migrations.AddConstraint(
            model_name='titlerating',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='rate only once'),
        ),
    ]
