# Generated by Django 5.1.7 on 2025-04-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_titleview_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='taggenre',
            options={'ordering': ['tag_name'], 'verbose_name': 'Тэг-жанр', 'verbose_name_plural': 'Тэги-жанры'},
        ),
    ]
