# Generated by Django 5.1.5 on 2025-03-01 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphictitle',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texttitle',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_name_rus',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_name_rus',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
