# Generated by Django 5.1.7 on 2025-03-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='graphictitlechapter',
            name='unique_chapter_per_graphic_title',
        ),
        migrations.RemoveConstraint(
            model_name='texttitlechapter',
            name='unique_chapter_per_text_title',
        ),
        migrations.AddConstraint(
            model_name='graphictitlechapter',
            constraint=models.UniqueConstraint(fields=('title', 'chapter_number'), name='unique_chapter_number_per_graphic_title'),
        ),
        migrations.AddConstraint(
            model_name='texttitlechapter',
            constraint=models.UniqueConstraint(fields=('title', 'chapter_number'), name='unique_chapter_number_per_text_title'),
        ),
    ]
