# Generated by Django 5.1.6 on 2025-02-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphictitle',
            old_name='author',
            new_name='title_author',
        ),
        migrations.RenameField(
            model_name='graphictitle',
            old_name='description',
            new_name='title_description',
        ),
        migrations.RenameField(
            model_name='texttitle',
            old_name='author',
            new_name='title_author',
        ),
        migrations.RenameField(
            model_name='texttitle',
            old_name='description',
            new_name='title_description',
        ),
        migrations.RemoveField(
            model_name='graphictitlechapter',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='texttitlechapter',
            name='Title',
        ),
        migrations.AddField(
            model_name='graphictitlechapter',
            name='chapter_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texttitlechapter',
            name='chapter_name',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphictitlechapter',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.graphictitle'),
        ),
        migrations.AlterField(
            model_name='texttitlechapter',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.texttitle'),
        ),
    ]
