# Generated by Django 5.1.7 on 2025-03-28 18:52

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_graphictitlechapter_unique_chapter_per_graphic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphictitle',
            name='title_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to=main.models.get_graphic_title_cover_path),
        ),
        migrations.AddField(
            model_name='texttitle',
            name='title_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to=main.models.get_text_title_cover_path),
        ),
    ]
