# Generated by Django 5.1.5 on 2025-03-01 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_graphictitle_added_at_texttitle_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphictitlechapter',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texttitlechapter',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
