# Generated by Django 5.1.6 on 2025-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_graphictitle_title_status_texttitle_title_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphictitle',
            name='title_status',
        ),
        migrations.RemoveField(
            model_name='texttitle',
            name='title_status',
        ),
        migrations.AddField(
            model_name='graphictitle',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphictitle',
            name='title_is_ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='texttitle',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='texttitle',
            name='title_is_ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_name_eng',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='title_name_rus',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_name_eng',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_name_rus',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
