# Generated by Django 5.1.6 on 2025-03-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_graphictitle_title_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphictitlechapter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='texttitlechapter',
            options={},
        ),
        migrations.RemoveField(
            model_name='graphictitlechapter',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='graphictitlechapter',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='graphictitlechapter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='graphictitlechapter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='texttitlechapter',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='texttitlechapter',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='texttitlechapter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='texttitlechapter',
            name='title',
        ),
        migrations.CreateModel(
            name='TitleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_number', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.texttitle')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='graphictitlechapter',
            name='titlechapter_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.titlechapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texttitlechapter',
            name='titlechapter_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.titlechapter'),
            preserve_default=False,
        ),
    ]
