# Generated by Django 5.1.6 on 2025-03-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_graphictitlechapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphictitle',
            name='title_name_eng',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='title_name_eng',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='titlechapter',
            constraint=models.UniqueConstraint(fields=('chapter_name', 'chapter_number'), name='unique_chapter_per_title'),
        ),
    ]
