# Generated by Django 5.1.6 on 2025-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_titlechapter_title_graphictitlechapter_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlechapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.AlterField(
            model_name='graphictitle',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='texttitle',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
        migrations.AddConstraint(
            model_name='graphictitle',
            constraint=models.CheckConstraint(condition=models.Q(('publication_year__lte', 2025), ('publication_year__gt', 0)), name='0 < publication year <= current year (graphic)'),
        ),
        migrations.AddConstraint(
            model_name='texttitle',
            constraint=models.CheckConstraint(condition=models.Q(('publication_year__lte', 2025), ('publication_year__gt', 0)), name='0 < publication year <= current year (text)'),
        ),
    ]
